Feat/sanity integration
wirayuda299/portfolio pull request #15
Opened 2023-09-15 01:52 UTC by wirayuda299

Hi @brandonetter 

here is list what i do in this branch

- Create schema for sanity
- Integrate sanity
- Create copy text function
- I make different layout with this web and sanity studio

2023-09-15 22:36 UTC, brandonetter requested changes
![image](https://github.com/wirayuda299/portfolio/assets/4108484/757ab3e3-4425-4044-bd78-4ab4a53b4b46)

The idea from the figma is that hovering over the section will color the icon. Not that only the firefox logo is colored.

You also have a weird color choice of making some of these sections pitch black. Please fix that to match the design.

2023-09-15 22:36 UTC, brandonetter commented on utils/caseStudies.ts
> +
```suggestion
	try {
		const diffProject = await client.fetch(
			`*[_type == "caseStudies" && _id != $id][0..1]`,{id}
		);
```
You can pass params to sanity by giving it a 'params' object as the second argument

2023-09-15 22:36 UTC, brandonetter commented on utils/caseStudies.ts
You could consider moving all of your Sanity queries into the sanity folder to keep things organized.

Perhaps an `actions` or `queries` folder with files named after each resource (like you already have).

2023-09-16 07:23 UTC, wirayuda299 commented on utils/caseStudies.ts
Thanks for your feedback🙏

2023-09-17 12:34 UTC, merged