Feat/services
wirayuda299/portfolio pull request #6
Opened 2023-09-07 09:30 UTC by wirayuda299

Create service section

2023-09-07 22:50 UTC, brandonetter requested changes
Small issue with the figma interpretation- but honestly this is looking BEAUTIFUL and spot-on with the design aside from that. Excellent work!

2023-09-07 22:50 UTC, brandonetter commented on components/Services/Card.tsx
The design isn't trying to show you that one of the cards is blue and lower, it's an implied animation. The expectation is that a mouse over will cause the animation. Same for the skills icons, the implication isn't that there's one that is full color. The idea is that a hover will cause it to become colored.

2023-09-07 22:59 UTC, wirayuda299 commented on components/Services/Card.tsx
ohh i see😁 

I will update my code, thanks for the feedback🙏

2023-09-07 23:15 UTC, brandonetter commented on components/Services/Card.tsx
No problem at all! You're not the only one, no worries!

2023-09-08 00:32 UTC, wirayuda299 commented on components/Services/Card.tsx
Thanks, is that same as well with work experience section? when the right card is hover it will show the shadow?

2023-09-08 08:56 UTC, brandonetter commented on components/Services/Card.tsx
Yes sir!

2023-09-08 08:56 UTC, merged